version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS:Service
      Properties:
        TaskDefinition: 'arn:aws:ecs:us-west-1:423037854251:task-definition/DemoAppTaskDefinition:1'
        LoadBalancerInfo:
          ContainerName: 'DemoAppContainer'
          ContainerPort: 8000
